apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-api
  description: Spring Boot core API service
  annotations:
    github.com/project-slug: rajesh-karavadi/core-api
spec:
  type: service
  lifecycle: production
  owner: devops-team
