apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "helm.fullname" . } }
  labels:
    app.kubernetes.io/name: core-api
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app.kubernetes.io/name: core-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: core-api
    spec:
      containers:
        - name: core-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.containerPort } }

          env:
            { { - toYaml .Values.env | nindent 12 } }

          resources:
            { { - toYaml .Values.resources | nindent 12 } }

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: { { .Values.containerPort } }
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: { { .Values.containerPort } }
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5